# frozen_string_literal: true

source 'http://rubygems.org'
ruby '2.5.3'
gem 'bcrypt'
gem 'coveralls'
gem 'natra'
gem 'oj'
gem 'pg', '~> 0.21.0'
gem 'puma'
gem 'rack-timeout'
gem 'rake'
gem 'require_all'
gem 'scout_apm'
gem 'seed-fu'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'tux'
group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
end
group :test do
  gem 'awesome_print'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'faker'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov'
end
